/*
 Navicat Premium Data Transfer

 Source Server         : 153.153.234.151
 Source Server Type    : Oracle
 Source Server Version : 110100
 Source Host           : 153.153.234.151:1521
 Source Schema         : SCOTT

 Target Server Type    : Oracle
 Target Server Version : 110100
 File Encoding         : 65001

 Date: 25/11/2019 11:29:03
*/


-- ----------------------------
-- Table structure for BONUS
-- ----------------------------
DROP TABLE "SCOTT"."BONUS";
CREATE TABLE "SCOTT"."BONUS" (
  "ENAME" VARCHAR2(10 BYTE) ,
  "JOB" VARCHAR2(9 BYTE) ,
  "SAL" NUMBER ,
  "COMM" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DEPT
-- ----------------------------
DROP TABLE "SCOTT"."DEPT";
CREATE TABLE "SCOTT"."DEPT" (
  "DEPTNO" NUMBER(2) NOT NULL ,
  "DNAME" VARCHAR2(14 BYTE) ,
  "LOC" VARCHAR2(13 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EMP
-- ----------------------------
DROP TABLE "SCOTT"."EMP";
CREATE TABLE "SCOTT"."EMP" (
  "EMPNO" NUMBER(4) NOT NULL ,
  "ENAME" VARCHAR2(10 BYTE) ,
  "JOB" VARCHAR2(9 BYTE) ,
  "MGR" NUMBER(4) ,
  "HIREDATE" DATE ,
  "SAL" NUMBER(7,2) ,
  "COMM" NUMBER(7,2) ,
  "DEPTNO" NUMBER(2) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EWE_ABLUENT
-- ----------------------------
DROP TABLE "SCOTT"."EWE_ABLUENT";
CREATE TABLE "SCOTT"."EWE_ABLUENT" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "ABLUENT_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "FUNC" VARCHAR2(64 BYTE) NOT NULL ,
  "ABLUENT_BGN" DATE ,
  "ABLUENT_END" DATE ,
  "USED_DAYS" VARCHAR2(64 BYTE) ,
  "WASHED_NUM" NUMBER(8) ,
  "STATUS" VARCHAR2(32 BYTE) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "ABLUENT_TYPE" NUMBER(8) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_ABLUENT"."USED_DAYS" IS '在更换的时候更新';
COMMENT ON COLUMN "SCOTT"."EWE_ABLUENT"."WASHED_NUM" IS '记录使用开始日期到结束日期期间的洗镜数量，在更换的时候更新';
COMMENT ON TABLE "SCOTT"."EWE_ABLUENT" IS '维护内镜的清洗槽或清洗机';

-- ----------------------------
-- Table structure for EWE_APPARATUS
-- ----------------------------
DROP TABLE "SCOTT"."EWE_APPARATUS";
CREATE TABLE "SCOTT"."EWE_APPARATUS" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "TANK_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "TANK_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "TANK_TYPE" NUMBER(8) NOT NULL ,
  "FUNC" VARCHAR2(64 BYTE) NOT NULL ,
  "CURRENT_STEP" NUMBER(8) NOT NULL ,
  "RFID_READER_ID" VARCHAR2(64 BYTE) NOT NULL ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "ABLUENT_TYPE" NUMBER(8) ,
  "DISINFECTANT_ID" VARCHAR2(32 BYTE) ,
  "DISINFECTANT_NAME" VARCHAR2(64 BYTE) ,
  "DISINFECTANT_BGN" DATE ,
  "ENZYME_ID" VARCHAR2(32 BYTE) ,
  "ENZYME_NAME" VARCHAR2(64 BYTE) ,
  "ENZYME_BGN" DATE ,
  "MACHINE_PROCESS" VARCHAR2(64 BYTE) ,
  "MODEL_TYPE" VARCHAR2(64 BYTE) DEFAULT 0
 NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_APPARATUS"."TANK_TYPE" IS '0是未指定、1是清洗机、2是清洗槽';
COMMENT ON COLUMN "SCOTT"."EWE_APPARATUS"."FUNC" IS '干燥、酶洗、消毒倍力曼初洗、末洗等自定义功能';
COMMENT ON COLUMN "SCOTT"."EWE_APPARATUS"."CURRENT_STEP" IS '0：未开始、1：侧漏、2：水洗、3：酶洗、4：消毒、5：冲洗、6：干燥';
COMMENT ON COLUMN "SCOTT"."EWE_APPARATUS"."RFID_READER_ID" IS '读卡器标识+读卡器的IP地址:DI20181019000001_153.153.153.166';
COMMENT ON TABLE "SCOTT"."EWE_APPARATUS" IS '维护内镜的清洗槽或清洗机';

-- ----------------------------
-- Table structure for EWE_ARRANGEMENT
-- ----------------------------
DROP TABLE "SCOTT"."EWE_ARRANGEMENT";
CREATE TABLE "SCOTT"."EWE_ARRANGEMENT" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "ARRANGE_DATE" DATE NOT NULL ,
  "EWE_USER_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "DUTY" NUMBER(8) NOT NULL ,
  "SCOPE_TYPE" NUMBER(8) ,
  "APPARATUS_ID" VARCHAR2(32 BYTE) ,
  "APPARATUS_NAME" VARCHAR2(64 BYTE) ,
  "PROCESS_STEP" VARCHAR2(64 BYTE) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."ID" IS '就是SYS_USER_ID，本系统所有权限全部等同于它';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."EWE_USER_ID" IS '如果是多个人，则用英文逗号隔开';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."EWE_USER_NAME" IS '洗消人员的姓名';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."DUTY" IS '0:无职责;1:负责流程;2:负责清洗器具;3:负责具体步骤；
如果负责流程，则使用"SCOPE_TYPE"；
如果负责清洗器具，则使用APPARATUS_ID和APPARATUS_NAME
如果负责具体步骤，例如“漂洗”，则使用"PROCESS"';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."SCOPE_TYPE" IS '0：未指定、1：胃镜、2：肠镜';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."APPARATUS_ID" IS '如果是个流程，则用英文逗号隔开';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."APPARATUS_NAME" IS '洗消用具名称';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT"."PROCESS_STEP" IS '如果是个流程，则用英文逗号隔开。0未开始、1：侧漏、2：水洗、3：酶洗、4：消毒、4：冲洗、5：干燥';
COMMENT ON TABLE "SCOTT"."EWE_ARRANGEMENT" IS '记录每周的排班信息，每周需要手动录入排班信息，否则就沿用本周排班，每周周末凌晨自动更新
如果负责流程，则使用"SCOPE_TYPE"；
如果负责清洗器具，则使用APPARATUS_ID和APPARATUS_NAME
如果负责具体步骤，例如“漂洗”，则使用"PROCESS"';

-- ----------------------------
-- Table structure for EWE_ARRANGEMENT_CURRENT
-- ----------------------------
DROP TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT";
CREATE TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "DUTY" NUMBER(8) NOT NULL ,
  "SCOPE_TYPE" NUMBER(8) ,
  "APPARATUS_ID" VARCHAR2(32 BYTE) ,
  "APPARATUS_NAME" VARCHAR2(64 BYTE) ,
  "PROCESS_STEP" NUMBER(8) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT_CURRENT"."ID" IS '就是SYS_USER_ID，本系统所有权限全部等同于它';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT_CURRENT"."EWE_USER_NAME" IS '洗消人员的姓名';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT_CURRENT"."DUTY" IS '0:无职责;1:负责流程;2:负责清洗器具;3:负责具体步骤；
如果负责流程，则使用"SCOPE_TYPE"；
如果负责清洗器具，则使用APPARATUS_ID和APPARATUS_NAME
如果负责具体步骤，例如 漂洗 ，则使用"PROCESS"
优先级:器具>步骤>流程';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT_CURRENT"."SCOPE_TYPE" IS '0：未指定、1：胃镜、2：肠镜';
COMMENT ON COLUMN "SCOTT"."EWE_ARRANGEMENT_CURRENT"."PROCESS_STEP" IS '0未开始、1：侧漏、2：水洗、3：酶洗、4：消毒、5：冲洗、6：干燥';
COMMENT ON TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" IS '1）记录当前人员的工作安排，每晚凌晨自动从排班信息里同步到这个表里；
2）只有管理员可以更改这个表';

-- ----------------------------
-- Table structure for EWE_ENDSCOPE
-- ----------------------------
DROP TABLE "SCOTT"."EWE_ENDSCOPE";
CREATE TABLE "SCOTT"."EWE_ENDSCOPE" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "SCOPE_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "RFID_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "SCOPE_TYPE" NUMBER(8) ,
  "SCOPE_INNER_NO" NUMBER(8) ,
  "CATEGORY" VARCHAR2(64 BYTE) ,
  "MANUFACTURE" VARCHAR2(64 BYTE) ,
  "PRICE" NUMBER(8,2) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_ENDSCOPE"."SCOPE_NO" IS '每个内镜的全球唯一编号';
COMMENT ON COLUMN "SCOTT"."EWE_ENDSCOPE"."RFID_NO" IS '射频卡编号';
COMMENT ON COLUMN "SCOTT"."EWE_ENDSCOPE"."SCOPE_TYPE" IS '0未指定、1胃镜、2肠镜';
COMMENT ON COLUMN "SCOTT"."EWE_ENDSCOPE"."SCOPE_INNER_NO" IS '操作间使用的内镜编号';
COMMENT ON TABLE "SCOTT"."EWE_ENDSCOPE" IS '只有内镜操作的人员，角色只分管理员和用户，不在此表中体现';

-- ----------------------------
-- Table structure for EWE_EQUIP_MAINTAINS
-- ----------------------------
DROP TABLE "SCOTT"."EWE_EQUIP_MAINTAINS";
CREATE TABLE "SCOTT"."EWE_EQUIP_MAINTAINS" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "MATERIAL_NO" VARCHAR2(32 BYTE) ,
  "MAINTAINS_PROJECT" VARCHAR2(512 BYTE) ,
  "MAINTAINS_RESON" VARCHAR2(512 BYTE) ,
  "MAINTAINS_RESULT" VARCHAR2(512 BYTE) ,
  "ENGINEER_NAME" VARCHAR2(64 BYTE) ,
  "MAINTAINS_TIME" DATE ,
  "MANUFACTURE" VARCHAR2(64 BYTE) ,
  "TEL" VARCHAR2(32 BYTE) ,
  "NURSE_NAME" VARCHAR2(64 BYTE) ,
  "SIGN_ID" VARCHAR2(32 BYTE) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON TABLE "SCOTT"."EWE_EQUIP_MAINTAINS" IS '洗消机维护管理,胃肠镜维护管理,工作站维护管理';

-- ----------------------------
-- Table structure for EWE_HOSPITAL_PROCESS
-- ----------------------------
DROP TABLE "SCOTT"."EWE_HOSPITAL_PROCESS";
CREATE TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "STEP_NO" NUMBER(8) NOT NULL ,
  "STEP_TYPE" NUMBER(8) NOT NULL ,
  "STEP_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "STEP_TIME_TYPE" NUMBER(8) NOT NULL ,
  "STEP_TIME" NUMBER(8) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_HOSPITAL_PROCESS"."STEP_NO" IS '0、2、3、4、5、6、7、8、9、10';
COMMENT ON COLUMN "SCOTT"."EWE_HOSPITAL_PROCESS"."STEP_TYPE" IS '0、1、2、3、4、5、6';
COMMENT ON COLUMN "SCOTT"."EWE_HOSPITAL_PROCESS"."STEP_NAME" IS '0未开始、1：测漏、2：水洗、3：酶洗、4：消毒、5：冲洗、6：干燥';
COMMENT ON COLUMN "SCOTT"."EWE_HOSPITAL_PROCESS"."STEP_TIME_TYPE" IS '1:定时、2:不定时';
COMMENT ON COLUMN "SCOTT"."EWE_HOSPITAL_PROCESS"."STEP_TIME" IS '如果定时需要填写，如果是不定时的就不需要填写';
COMMENT ON TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" IS '有的医院有侧漏，有的医院没测漏，每个医院的流程不一样，选取每个清洗流程所属的步骤';

-- ----------------------------
-- Table structure for EWE_MACHINE
-- ----------------------------
DROP TABLE "SCOTT"."EWE_MACHINE";
CREATE TABLE "SCOTT"."EWE_MACHINE" (
  "ID" VARCHAR2(64 BYTE) NOT NULL ,
  "MACHINE_NAME" VARCHAR2(64 BYTE) ,
  "MACHINE_DESCRIBE" VARCHAR2(64 BYTE) ,
  "CARD_ID" VARCHAR2(64 BYTE) ,
  "PRE_PROCESS" VARCHAR2(64 BYTE) ,
  "MODEL_NAME" VARCHAR2(64 BYTE) ,
  "CREATE_TIME" DATE ,
  "UPDATE_TIME" DATE ,
  "POST_PROCESS" VARCHAR2(64 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."ID" IS '机洗主键';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."MACHINE_NAME" IS '前置流程名称';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."MACHINE_DESCRIBE" IS '机洗描述';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."CARD_ID" IS '流程卡id';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."PRE_PROCESS" IS '前置流程id';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."MODEL_NAME" IS '模式名称';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE"."POST_PROCESS" IS '后置流程';

-- ----------------------------
-- Table structure for EWE_MACHINE_PROCESS
-- ----------------------------
DROP TABLE "SCOTT"."EWE_MACHINE_PROCESS";
CREATE TABLE "SCOTT"."EWE_MACHINE_PROCESS" (
  "ID" VARCHAR2(64 BYTE) NOT NULL ,
  "LEAD_PROCESS_TYPE" NUMBER ,
  "CURRENT_STEP" VARCHAR2(255 BYTE) ,
  "CREATE_TIME" DATE ,
  "UPDATE_TIME" DATE ,
  "STAGE_NAME" VARCHAR2(255 BYTE) ,
  "PROCESS_ID" VARCHAR2(64 BYTE) ,
  "DURATION" NUMBER ,
  "MACHINE_TYPE" VARCHAR2(64 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."ID" IS '机洗流程主键';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."LEAD_PROCESS_TYPE" IS '是否是主流程0是1不是';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."CURRENT_STEP" IS '流程内容(机洗\漂洗)';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."STAGE_NAME" IS '阶段名称';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."PROCESS_ID" IS '对应主流程ID';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."DURATION" IS '步骤持续时间';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS"."MACHINE_TYPE" IS '机型';

-- ----------------------------
-- Table structure for EWE_MACHINE_PROCESS_RELATION
-- ----------------------------
DROP TABLE "SCOTT"."EWE_MACHINE_PROCESS_RELATION";
CREATE TABLE "SCOTT"."EWE_MACHINE_PROCESS_RELATION" (
  "MACHINE_ID" VARCHAR2(64 BYTE) NOT NULL ,
  "MACHINE_PROCESS_ID" VARCHAR2(64 BYTE) NOT NULL ,
  "CLEANING_TIME" NUMBER NOT NULL ,
  "SEQ" NUMBER NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS_RELATION"."MACHINE_ID" IS '流程主表id';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS_RELATION"."MACHINE_PROCESS_ID" IS '流程主表id';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS_RELATION"."CLEANING_TIME" IS '清洗时间(单位:秒)';
COMMENT ON COLUMN "SCOTT"."EWE_MACHINE_PROCESS_RELATION"."SEQ" IS '顺序(1,2,3,4,5,6,7,8,9)';

-- ----------------------------
-- Table structure for EWE_MATERIAL
-- ----------------------------
DROP TABLE "SCOTT"."EWE_MATERIAL";
CREATE TABLE "SCOTT"."EWE_MATERIAL" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "MATERIAL_NO" VARCHAR2(32 BYTE) ,
  "MATERIAL_NAME" VARCHAR2(64 BYTE) ,
  "CATEGORY" VARCHAR2(64 BYTE) ,
  "MANUFACTURE" VARCHAR2(64 BYTE) ,
  "PRICE" NUMBER(8,2) ,
  "UNIT" VARCHAR2(32 BYTE) ,
  "NUM_SUM" NUMBER(8) ,
  "NUM_USED" NUMBER(8) ,
  "NUM_REMAIN" NUMBER(8) ,
  "TRANSPOSING_RECORD" BLOB ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "RFID_NO" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_MATERIAL"."MATERIAL_NO" IS '物料的编号';
COMMENT ON TABLE "SCOTT"."EWE_MATERIAL" IS '洗消耗材';

-- ----------------------------
-- Table structure for EWE_MATERIAL_ENDSCOPE_REL
-- ----------------------------
DROP TABLE "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL";
CREATE TABLE "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "MATERIAL_NO" VARCHAR2(32 BYTE) ,
  "MATERIAL_NAME" VARCHAR2(64 BYTE) ,
  "SCOPE_INNER_NO" NUMBER(8) ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL"."MATERIAL_NO" IS '物料的编号';
COMMENT ON COLUMN "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL"."SCOPE_INNER_NO" IS '操作间使用的内镜编号';
COMMENT ON TABLE "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL" IS '毛刷等';

-- ----------------------------
-- Table structure for EWE_MATERIAL_USE_RECORD
-- ----------------------------
DROP TABLE "SCOTT"."EWE_MATERIAL_USE_RECORD";
CREATE TABLE "SCOTT"."EWE_MATERIAL_USE_RECORD" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "MATERIAL_NO" VARCHAR2(32 BYTE) ,
  "MATERIAL_NAME" VARCHAR2(64 BYTE) ,
  "SCOPE_INNER_NO" NUMBER(8) ,
  "TANK_NO" VARCHAR2(32 BYTE) ,
  "TANK_NAME" VARCHAR2(64 BYTE) ,
  "EWE_USER_ID" VARCHAR2(32 BYTE) ,
  "EWE_USER_NAME" VARCHAR2(64 BYTE) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "EWE_TRACE_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 917504 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_MATERIAL_USE_RECORD"."MATERIAL_NO" IS '物料的编号';
COMMENT ON COLUMN "SCOTT"."EWE_MATERIAL_USE_RECORD"."SCOPE_INNER_NO" IS '操作间使用的内镜编号';
COMMENT ON COLUMN "SCOTT"."EWE_MATERIAL_USE_RECORD"."EWE_USER_NAME" IS '洗消人员的姓名';
COMMENT ON TABLE "SCOTT"."EWE_MATERIAL_USE_RECORD" IS '物料的使用记录';

-- ----------------------------
-- Table structure for EWE_PROCESS
-- ----------------------------
DROP TABLE "SCOTT"."EWE_PROCESS";
CREATE TABLE "SCOTT"."EWE_PROCESS" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_ENDSCOPE_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "SCOPE_TYPE" NUMBER(8) ,
  "SCOPE_INNER_NO" NUMBER(8) ,
  "APPARATUS_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "CURRENT_STEP" NUMBER(8) NOT NULL ,
  "WASH_BGN_TIME" DATE ,
  "WASH_END_TIME" DATE ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "EWE_TRACE_ID" VARCHAR2(32 BYTE) ,
  "TANK_NAME" VARCHAR2(64 BYTE) ,
  "TANK_TYPE" NUMBER(8) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 7340032 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_PROCESS"."SCOPE_TYPE" IS '0未指定、1胃镜、2肠镜';
COMMENT ON COLUMN "SCOTT"."EWE_PROCESS"."SCOPE_INNER_NO" IS '操作间使用的内镜编号';
COMMENT ON COLUMN "SCOTT"."EWE_PROCESS"."APPARATUS_NO" IS '机器的唯一编号';
COMMENT ON COLUMN "SCOTT"."EWE_PROCESS"."CURRENT_STEP" IS '0未开始、1：侧漏、2：水洗、3：酶洗、4：消毒、4：冲洗、5：干燥、6,：结束';
COMMENT ON COLUMN "SCOTT"."EWE_PROCESS"."TANK_TYPE" IS '0是未指定、1是清洗机、2是清洗槽';
COMMENT ON TABLE "SCOTT"."EWE_PROCESS" IS '记录和显示洗消的步骤，从第一个节点开始，最后一个节点结束，开始的时候创建记录，每个流程结束都要新建一个流程（做到每个流程可追溯人员），结束的时候升级状态到“结束”';

-- ----------------------------
-- Table structure for EWE_RFID
-- ----------------------------
DROP TABLE "SCOTT"."EWE_RFID";
CREATE TABLE "SCOTT"."EWE_RFID" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "RFID_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "OPEN_TIME" DATE ,
  "CATEGORY" VARCHAR2(64 BYTE) ,
  "MANUFACTURE" VARCHAR2(64 BYTE) ,
  "PRICE" NUMBER(8,2) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "RFID_SERIAL" VARCHAR2(32 BYTE) ,
  "CARD_TYPE" VARCHAR2(64 BYTE) ,
  "MODEL_ID" VARCHAR2(64 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_RFID"."RFID_NO" IS '射频卡编号';
COMMENT ON COLUMN "SCOTT"."EWE_RFID"."RFID_SERIAL" IS '卡上的序列号';
COMMENT ON COLUMN "SCOTT"."EWE_RFID"."CARD_TYPE" IS '卡类型';
COMMENT ON COLUMN "SCOTT"."EWE_RFID"."MODEL_ID" IS '模式ID';
COMMENT ON TABLE "SCOTT"."EWE_RFID" IS '管理无线设备设备';

-- ----------------------------
-- Table structure for EWE_SYS_USER
-- ----------------------------
DROP TABLE "SCOTT"."EWE_SYS_USER";
CREATE TABLE "SCOTT"."EWE_SYS_USER" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "UPMS_USER_ID" VARCHAR2(32 BYTE) ,
  "EWE_USER_ID" VARCHAR2(32 BYTE) ,
  "NAME_USER" VARCHAR2(64 BYTE) ,
  "PASSWORD" VARCHAR2(32 BYTE) ,
  "ROLE" NUMBER(8) ,
  "STATE" NUMBER(8) ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."ID" IS '就是SYS_USER_ID，本系统所有权限全部等同于它';
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."UPMS_USER_ID" IS '系统平台的ID';
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."EWE_USER_ID" IS '医生id';
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."NAME_USER" IS '用户名';
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."PASSWORD" IS '密码';
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."ROLE" IS '1管理员、2医生、3护工、4工人';
COMMENT ON COLUMN "SCOTT"."EWE_SYS_USER"."STATE" IS '状态0-禁用;1-启用';

-- ----------------------------
-- Table structure for EWE_TRACE
-- ----------------------------
DROP TABLE "SCOTT"."EWE_TRACE";
CREATE TABLE "SCOTT"."EWE_TRACE" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_ENDSCOPE_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "SCOPE_TYPE" NUMBER(8) ,
  "SCOPE_INNER_NO" NUMBER(8) ,
  "SCOPE_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "EWE_USER_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "WASH_BGN_TIME" DATE ,
  "WASH_END_TIME" DATE ,
  "PATIENT_ID" VARCHAR2(32 BYTE) ,
  "PATIENT_NAME" VARCHAR2(64 BYTE) ,
  "PATIENT_CURRENT_AGE" VARCHAR2(8 BYTE) ,
  "DOCTOR_NO" VARCHAR2(32 BYTE) ,
  "DOCTOR_NAME" VARCHAR2(64 BYTE) ,
  "ENDOSCOPY_CHK_TIME" DATE ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "TYPE" NUMBER(8) ,
  "WARNING_COUNTAGION4" VARCHAR2(200 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 2097152 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_TRACE"."SCOPE_TYPE" IS '0未指定、1胃镜、2肠镜';
COMMENT ON COLUMN "SCOTT"."EWE_TRACE"."SCOPE_INNER_NO" IS '操作间使用的内镜编号';
COMMENT ON COLUMN "SCOTT"."EWE_TRACE"."SCOPE_NO" IS '机器的唯一编号';
COMMENT ON TABLE "SCOTT"."EWE_TRACE" IS '用于记录洗消的医生姓名、患者姓名、患者身份证号、患者当前年龄、镜子编号、检测时间开始和结束时间的追溯系统';

-- ----------------------------
-- Table structure for EWE_USER
-- ----------------------------
DROP TABLE "SCOTT"."EWE_USER";
CREATE TABLE "SCOTT"."EWE_USER" (
  "ID" VARCHAR2(32 BYTE) NOT NULL ,
  "USER_NO" VARCHAR2(32 BYTE) NOT NULL ,
  "USER_NAME" VARCHAR2(64 BYTE) NOT NULL ,
  "UPMS_ORGANIZATION_ID" NUMBER(9) ,
  "CREATE_TIME" DATE ,
  "SYS_USER_ID" VARCHAR2(32 BYTE) ,
  "RFID_NO" VARCHAR2(32 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."EWE_USER"."USER_NO" IS '身份证号';
COMMENT ON COLUMN "SCOTT"."EWE_USER"."USER_NAME" IS '洗消人员的姓名';
COMMENT ON COLUMN "SCOTT"."EWE_USER"."RFID_NO" IS '无线设备编号';
COMMENT ON TABLE "SCOTT"."EWE_USER" IS '只有内镜操作的人员，角色只分管理员和用户，不在此表中体现';

-- ----------------------------
-- Table structure for SALGRADE
-- ----------------------------
DROP TABLE "SCOTT"."SALGRADE";
CREATE TABLE "SCOTT"."SALGRADE" (
  "GRADE" NUMBER ,
  "LOSAL" NUMBER ,
  "HISAL" NUMBER 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for UPMS_LOG
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_LOG";
CREATE TABLE "SCOTT"."UPMS_LOG" (
  "LOG_ID" VARCHAR2(32 BYTE) NOT NULL ,
  "DESCRIPTION" VARCHAR2(256 BYTE) ,
  "USERNAME" VARCHAR2(64 BYTE) ,
  "START_TIME" NUMBER(38) ,
  "SPEND_TIME" NUMBER(38) ,
  "BASE_PATH" VARCHAR2(100 BYTE) ,
  "URI" VARCHAR2(2048 BYTE) ,
  "URL" VARCHAR2(2048 BYTE) ,
  "METHOD" VARCHAR2(32 BYTE) ,
  "PARAMETER" CLOB ,
  "USER_AGENT" VARCHAR2(512 BYTE) ,
  "IP" VARCHAR2(32 BYTE) ,
  "RESULT" CLOB ,
  "PERMISSIONS" VARCHAR2(256 BYTE) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 2617245696 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."LOG_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."DESCRIPTION" IS '操作描述';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."USERNAME" IS '操作用户';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."START_TIME" IS '操作时间';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."SPEND_TIME" IS '消耗时间';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."BASE_PATH" IS '根路径';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."URI" IS 'URI';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."URL" IS 'URL';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."METHOD" IS '请求类型';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."PARAMETER" IS '请求参数';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."USER_AGENT" IS '用户标识';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."IP" IS 'IP地址';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."RESULT" IS '响应结果';
COMMENT ON COLUMN "SCOTT"."UPMS_LOG"."PERMISSIONS" IS '权限值';
COMMENT ON TABLE "SCOTT"."UPMS_LOG" IS '操作日志';

-- ----------------------------
-- Table structure for UPMS_ORGANIZATION
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_ORGANIZATION";
CREATE TABLE "SCOTT"."UPMS_ORGANIZATION" (
  "ORGANIZATION_ID" NUMBER(9) NOT NULL ,
  "PID" NUMBER(38) ,
  "NAME" VARCHAR2(64 BYTE) ,
  "DESCRIPTION" VARCHAR2(1024 BYTE) ,
  "CTIME" NUMBER(38) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_ORGANIZATION"."ORGANIZATION_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_ORGANIZATION"."PID" IS '所属上级';
COMMENT ON COLUMN "SCOTT"."UPMS_ORGANIZATION"."NAME" IS '组织名称';
COMMENT ON COLUMN "SCOTT"."UPMS_ORGANIZATION"."DESCRIPTION" IS '组织描述';
COMMENT ON COLUMN "SCOTT"."UPMS_ORGANIZATION"."CTIME" IS '创建时间';
COMMENT ON TABLE "SCOTT"."UPMS_ORGANIZATION" IS '组织';

-- ----------------------------
-- Table structure for UPMS_PERMISSION
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_PERMISSION";
CREATE TABLE "SCOTT"."UPMS_PERMISSION" (
  "PERMISSION_ID" NUMBER(9) NOT NULL ,
  "SYSTEM_ID" NUMBER(38) NOT NULL ,
  "PID" NUMBER(38) ,
  "NAME" VARCHAR2(64 BYTE) ,
  "TYPE" NUMBER(38) ,
  "PERMISSION_VALUE" VARCHAR2(50 BYTE) ,
  "URI" VARCHAR2(100 BYTE) ,
  "ICON" VARCHAR2(50 BYTE) ,
  "STATUS" NUMBER(38) ,
  "CTIME" NUMBER(38) ,
  "ORDERS" NUMBER(38) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."PERMISSION_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."SYSTEM_ID" IS '所属系统';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."PID" IS '所属上级';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."NAME" IS '名称';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."TYPE" IS '类型(1:目录,2:菜单,3:按钮)';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."PERMISSION_VALUE" IS '权限值';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."URI" IS '路径';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."ICON" IS '图标';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."STATUS" IS '状态(0:禁止,1:正常)';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."CTIME" IS '创建时间';
COMMENT ON COLUMN "SCOTT"."UPMS_PERMISSION"."ORDERS" IS '排序';
COMMENT ON TABLE "SCOTT"."UPMS_PERMISSION" IS '权限';

-- ----------------------------
-- Table structure for UPMS_ROLE
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_ROLE";
CREATE TABLE "SCOTT"."UPMS_ROLE" (
  "ROLE_ID" NUMBER(9) NOT NULL ,
  "NAME" VARCHAR2(20 BYTE) ,
  "TITLE" VARCHAR2(20 BYTE) ,
  "DESCRIPTION" VARCHAR2(1000 BYTE) ,
  "CTIME" NUMBER(38) NOT NULL ,
  "ORDERS" NUMBER(38) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE"."ROLE_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE"."NAME" IS '角色名称';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE"."TITLE" IS '角色标题';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE"."DESCRIPTION" IS '角色描述';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE"."CTIME" IS '创建时间';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE"."ORDERS" IS '排序';
COMMENT ON TABLE "SCOTT"."UPMS_ROLE" IS '角色';

-- ----------------------------
-- Table structure for UPMS_ROLE_PERMISSION
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_ROLE_PERMISSION";
CREATE TABLE "SCOTT"."UPMS_ROLE_PERMISSION" (
  "ROLE_PERMISSION_ID" NUMBER(9) NOT NULL ,
  "ROLE_ID" NUMBER(38) NOT NULL ,
  "PERMISSION_ID" NUMBER(38) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE_PERMISSION"."ROLE_PERMISSION_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE_PERMISSION"."ROLE_ID" IS '角色编号';
COMMENT ON COLUMN "SCOTT"."UPMS_ROLE_PERMISSION"."PERMISSION_ID" IS '权限编号';
COMMENT ON TABLE "SCOTT"."UPMS_ROLE_PERMISSION" IS '角色权限关联表';

-- ----------------------------
-- Table structure for UPMS_SYSTEM
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_SYSTEM";
CREATE TABLE "SCOTT"."UPMS_SYSTEM" (
  "SYSTEM_ID" NUMBER(9) NOT NULL ,
  "ICON" VARCHAR2(50 BYTE) ,
  "BANNER" VARCHAR2(150 BYTE) ,
  "THEME" VARCHAR2(50 BYTE) ,
  "BASEPATH" VARCHAR2(100 BYTE) ,
  "STATUS" NUMBER(38) ,
  "NAME" VARCHAR2(30 BYTE) ,
  "TITLE" VARCHAR2(50 BYTE) ,
  "DESCRIPTION" VARCHAR2(1024 BYTE) ,
  "CTIME" NUMBER(38) ,
  "ORDERS" NUMBER(38) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."SYSTEM_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."ICON" IS '图标';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."BANNER" IS '背景';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."THEME" IS '主题';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."BASEPATH" IS '根目录';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."STATUS" IS '状态(-1:黑名单,1:正常)';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."NAME" IS '系统名称';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."TITLE" IS '系统标题';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."DESCRIPTION" IS '系统描述';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."CTIME" IS '创建时间';
COMMENT ON COLUMN "SCOTT"."UPMS_SYSTEM"."ORDERS" IS '排序';
COMMENT ON TABLE "SCOTT"."UPMS_SYSTEM" IS '系统';

-- ----------------------------
-- Table structure for UPMS_USER
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_USER";
CREATE TABLE "SCOTT"."UPMS_USER" (
  "USER_ID" NUMBER(9) NOT NULL ,
  "USERNAME" VARCHAR2(64 BYTE) NOT NULL ,
  "PASSWORD" VARCHAR2(32 BYTE) NOT NULL ,
  "SALT" VARCHAR2(32 BYTE) ,
  "REALNAME" VARCHAR2(64 BYTE) ,
  "AVATAR" VARCHAR2(256 BYTE) ,
  "PHONE" VARCHAR2(32 BYTE) ,
  "EMAIL" VARCHAR2(64 BYTE) ,
  "SEX" NUMBER(38) ,
  "LOCKED" NUMBER(38) ,
  "CTIME" NUMBER(38) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."USER_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."USERNAME" IS '帐号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."PASSWORD" IS '密码MD5(密码+盐)';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."SALT" IS '盐';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."REALNAME" IS '姓名';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."AVATAR" IS '头像';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."PHONE" IS '电话';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."EMAIL" IS '邮箱';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."SEX" IS '性别';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."LOCKED" IS '状态(0:正常,1:锁定)';
COMMENT ON COLUMN "SCOTT"."UPMS_USER"."CTIME" IS '创建时间';
COMMENT ON TABLE "SCOTT"."UPMS_USER" IS '用户';

-- ----------------------------
-- Table structure for UPMS_USER_ORGANIZATION
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_USER_ORGANIZATION";
CREATE TABLE "SCOTT"."UPMS_USER_ORGANIZATION" (
  "USER_ORGANIZATION_ID" NUMBER(9) NOT NULL ,
  "USER_ID" NUMBER(38) NOT NULL ,
  "ORGANIZATION_ID" NUMBER(38) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_USER_ORGANIZATION"."USER_ORGANIZATION_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_ORGANIZATION"."USER_ID" IS '用户编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_ORGANIZATION"."ORGANIZATION_ID" IS '组织编号';
COMMENT ON TABLE "SCOTT"."UPMS_USER_ORGANIZATION" IS '用户组织关联表';

-- ----------------------------
-- Table structure for UPMS_USER_PERMISSION
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_USER_PERMISSION";
CREATE TABLE "SCOTT"."UPMS_USER_PERMISSION" (
  "USER_PERMISSION_ID" NUMBER(9) NOT NULL ,
  "USER_ID" NUMBER(38) NOT NULL ,
  "PERMISSION_ID" NUMBER(38) NOT NULL ,
  "TYPE" NUMBER(38) NOT NULL 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_USER_PERMISSION"."USER_PERMISSION_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_PERMISSION"."USER_ID" IS '用户编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_PERMISSION"."PERMISSION_ID" IS '权限编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_PERMISSION"."TYPE" IS '权限类型(-1:减权限,1:增权限)';
COMMENT ON TABLE "SCOTT"."UPMS_USER_PERMISSION" IS '用户权限关联表';

-- ----------------------------
-- Table structure for UPMS_USER_ROLE
-- ----------------------------
DROP TABLE "SCOTT"."UPMS_USER_ROLE";
CREATE TABLE "SCOTT"."UPMS_USER_ROLE" (
  "USER_ROLE_ID" NUMBER(9) NOT NULL ,
  "USER_ID" NUMBER(38) NOT NULL ,
  "ROLE_ID" NUMBER(38) 
)
TABLESPACE "USERS"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;
COMMENT ON COLUMN "SCOTT"."UPMS_USER_ROLE"."USER_ROLE_ID" IS '编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_ROLE"."USER_ID" IS '用户编号';
COMMENT ON COLUMN "SCOTT"."UPMS_USER_ROLE"."ROLE_ID" IS '角色编号';
COMMENT ON TABLE "SCOTT"."UPMS_USER_ROLE" IS '用户角色关联表';

-- ----------------------------
-- Function structure for GET_ORDER_CODE
-- ----------------------------
CREATE OR REPLACE
FUNCTION "SCOTT"."GET_ORDER_CODE" AS
BEGIN
   OPEN get_max_order_no;
   FETCH get_max_order_no INTO v_requestcode;
   CLOSE get_max_order_no;

 IF v_requestcode IS NULL THEN
   v_requestcode := NVL(v_requestcode,0);-- NVL()函数：当v_requestcode为NULL时，取0作为值
 END IF;
   v_requestcode:= v_requestcode;-- 将游标中截取到的值加1，然后向左填充0，生成 001,002...00n 三位数的 序号； lpad()函数：向左填充
   v_mca_no:='HG'||to_char(sysdate,'YYYYMMDDHH24MISS')||v_requestcode; -- 最终生成的申请单号（如：MA20170422001；MA20170422002;...MA2017042200N ）
   RETURN v_mca_no;
END;
/

-- ----------------------------
-- Function structure for MYJOBPRO
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SCOTT"."MYJOBPRO" AS
begin
   for x in p_account_cur loop
        accountId:=x.LABEL_AI_ACCOUNT_ID;
        dbms_output.put_line(accountId);
        select to_char(END_TIME) into times 
        from( 
        SELECT * from TR_ORDER_PAYINFO 
        where BELONG_2_ID = accountId 
        ORDER BY END_TIME desc) 
        where rownum=1;
        if null = times then
          select to_char(ti.Create_Time) into times 
          from TR_IMG_LABEL_REL t 
          inner join TR_IMG_LABEL ti 
          ON t.Img_Label_Id = ti.ID 
          where ti.Label_Ai_Account_Id = accountId 
          AND rownum=1
          ORDER BY ti.Create_Time ASC;
        end if;
        SLECTACCOUNTJOB(accountId,times);
        dbms_output.put_line('************');
   end loop;
end myjobpro;
/

-- ----------------------------
-- Function structure for SLECTACCOUNTJOB
-- ----------------------------
CREATE OR REPLACE
PROCEDURE "SCOTT"."SLECTACCOUNTJOB" AS
begin
   for x in s_cur loop
     partsName:=x.partsName;
     labelCount:=x.labelCount;
     dbms_output.put_line(partsName||' '||labelCount);
   end loop;

   for i in p_cur loop
      pay:=i.pay;
      dbms_output.put_line(pay);
   end loop;

    insert into TR_ORDER_PAYINFO
    values(sys_guid(),get_order_code,accountId,accountId,times,
    to_char(SYSDATE,'yyyy-mm-dd hh:MM:ss'),pay,null,null,null,null,null,'待支付',null,null,null,null,null);
end slectAccountJob;
/

-- ----------------------------
-- Sequence structure for DEP_SEQUENCE
-- ----------------------------
DROP SEQUENCE "SCOTT"."DEP_SEQUENCE";
CREATE SEQUENCE "SCOTT"."DEP_SEQUENCE" MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_ORGANIZATION_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_ORGANIZATION_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_ORGANIZATION_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_PERMISSION_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_PERMISSION_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_PERMISSION_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_ROLE_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_ROLE_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_ROLE_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_ROLE_PERMISSION_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_ROLE_PERMISSION_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_ROLE_PERMISSION_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_SYSTEM_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_SYSTEM_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_SYSTEM_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_USER_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_USER_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_USER_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_USER_ORGANIZATION_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_USER_ORGANIZATION_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_USER_ORGANIZATION_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_USER_PERMISSION_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_USER_PERMISSION_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_USER_PERMISSION_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Sequence structure for UPMS_USER_ROLE_ID_SEQ
-- ----------------------------
DROP SEQUENCE "SCOTT"."UPMS_USER_ROLE_ID_SEQ";
CREATE SEQUENCE "SCOTT"."UPMS_USER_ROLE_ID_SEQ" MINVALUE 10000 MAXVALUE 99999999999999 INCREMENT BY 1 CACHE 20;

-- ----------------------------
-- Primary Key structure for table DEPT
-- ----------------------------
ALTER TABLE "SCOTT"."DEPT" ADD CONSTRAINT "PK_DEPT" PRIMARY KEY ("DEPTNO");

-- ----------------------------
-- Primary Key structure for table EMP
-- ----------------------------
ALTER TABLE "SCOTT"."EMP" ADD CONSTRAINT "PK_EMP" PRIMARY KEY ("EMPNO");

-- ----------------------------
-- Primary Key structure for table EWE_ABLUENT
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ABLUENT" ADD CONSTRAINT "PK_EWE_ABLUENT" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_ABLUENT
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ABLUENT" ADD CONSTRAINT "SYS_C0010167" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ABLUENT" ADD CONSTRAINT "SYS_C0010168" CHECK ("ABLUENT_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ABLUENT" ADD CONSTRAINT "SYS_C0010169" CHECK ("FUNC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_APPARATUS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "PK_EWE_APPARATUS" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_APPARATUS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010171" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010172" CHECK ("TANK_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010173" CHECK ("TANK_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010174" CHECK ("TANK_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010175" CHECK ("FUNC" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010176" CHECK ("CURRENT_STEP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010177" CHECK ("RFID_READER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_APPARATUS" ADD CONSTRAINT "SYS_C0010547" CHECK ("MODEL_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_ARRANGEMENT
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT" ADD CONSTRAINT "PK_EWE_ARRANGEMENT" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_ARRANGEMENT
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT" ADD CONSTRAINT "SYS_C0010179" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT" ADD CONSTRAINT "SYS_C0010180" CHECK ("ARRANGE_DATE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT" ADD CONSTRAINT "SYS_C0010181" CHECK ("EWE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT" ADD CONSTRAINT "SYS_C0010182" CHECK ("EWE_USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT" ADD CONSTRAINT "SYS_C0010183" CHECK ("DUTY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_ARRANGEMENT_CURRENT
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" ADD CONSTRAINT "PK_EWE_ARRANGEMENT_CURRENT" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_ARRANGEMENT_CURRENT
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" ADD CONSTRAINT "SYS_C0010185" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" ADD CONSTRAINT "SYS_C0010186" CHECK ("EWE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" ADD CONSTRAINT "SYS_C0010187" CHECK ("EWE_USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ARRANGEMENT_CURRENT" ADD CONSTRAINT "SYS_C0010188" CHECK ("DUTY" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_ENDSCOPE
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ENDSCOPE" ADD CONSTRAINT "PK_EWE_ENDSCOPE" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_ENDSCOPE
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_ENDSCOPE" ADD CONSTRAINT "SYS_C0010190" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ENDSCOPE" ADD CONSTRAINT "SYS_C0010191" CHECK ("SCOPE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_ENDSCOPE" ADD CONSTRAINT "SYS_C0010192" CHECK ("RFID_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_EQUIP_MAINTAINS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_EQUIP_MAINTAINS" ADD CONSTRAINT "PK_EWE_EQUIP_MAINTAINS" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_EQUIP_MAINTAINS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_EQUIP_MAINTAINS" ADD CONSTRAINT "SYS_C0010194" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_HOSPITAL_PROCESS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "PK_EWE_HOSPITAL_PROCESS" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_HOSPITAL_PROCESS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0010196" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0010197" CHECK ("STEP_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0010198" CHECK ("STEP_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0010199" CHECK ("STEP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0010200" CHECK ("STEP_TIME_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0011830" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0011831" CHECK ("STEP_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0011832" CHECK ("STEP_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0011833" CHECK ("STEP_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_HOSPITAL_PROCESS" ADD CONSTRAINT "SYS_C0011834" CHECK ("STEP_TIME_TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EWE_MACHINE
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MACHINE" ADD CONSTRAINT "SYS_C0010505" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EWE_MACHINE_PROCESS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MACHINE_PROCESS" ADD CONSTRAINT "SYS_C0010506" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Checks structure for table EWE_MACHINE_PROCESS_RELATION
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MACHINE_PROCESS_RELATION" ADD CONSTRAINT "SYS_C0010507" CHECK ("MACHINE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_MACHINE_PROCESS_RELATION" ADD CONSTRAINT "SYS_C0010508" CHECK ("MACHINE_PROCESS_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_MACHINE_PROCESS_RELATION" ADD CONSTRAINT "SYS_C0010509" CHECK ("CLEANING_TIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_MACHINE_PROCESS_RELATION" ADD CONSTRAINT "SYS_C0010510" CHECK ("SEQ" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_MATERIAL
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MATERIAL" ADD CONSTRAINT "PK_EWE_MATERIAL" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_MATERIAL
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MATERIAL" ADD CONSTRAINT "SYS_C0010207" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_MATERIAL_ENDSCOPE_REL
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL" ADD CONSTRAINT "PK_EWE_MATERIAL_ENDSCOPE_REL" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_MATERIAL_ENDSCOPE_REL
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MATERIAL_ENDSCOPE_REL" ADD CONSTRAINT "SYS_C0010209" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_MATERIAL_USE_RECORD
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MATERIAL_USE_RECORD" ADD CONSTRAINT "PK_EWE_MATERIAL_USE_RECORD" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_MATERIAL_USE_RECORD
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_MATERIAL_USE_RECORD" ADD CONSTRAINT "SYS_C0010211" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_PROCESS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "PK_EWE_PROCESS" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_PROCESS
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "SYS_C0010213" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "SYS_C0010214" CHECK ("EWE_ENDSCOPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "SYS_C0010215" CHECK ("APPARATUS_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "SYS_C0010216" CHECK ("EWE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "SYS_C0010217" CHECK ("EWE_USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_PROCESS" ADD CONSTRAINT "SYS_C0010218" CHECK ("CURRENT_STEP" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_RFID
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_RFID" ADD CONSTRAINT "PK_EWE_RFID" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_RFID
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_RFID" ADD CONSTRAINT "SYS_C0010220" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_RFID" ADD CONSTRAINT "SYS_C0010221" CHECK ("RFID_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_SYS_USER
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_SYS_USER" ADD CONSTRAINT "PK_EWE_SYS_USER" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_SYS_USER
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_SYS_USER" ADD CONSTRAINT "SYS_C0010223" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_TRACE
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_TRACE" ADD CONSTRAINT "PK_EWE_TRACE" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_TRACE
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_TRACE" ADD CONSTRAINT "SYS_C0010225" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_TRACE" ADD CONSTRAINT "SYS_C0010226" CHECK ("EWE_ENDSCOPE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_TRACE" ADD CONSTRAINT "SYS_C0010227" CHECK ("SCOPE_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_TRACE" ADD CONSTRAINT "SYS_C0010228" CHECK ("EWE_USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_TRACE" ADD CONSTRAINT "SYS_C0010229" CHECK ("EWE_USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table EWE_USER
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_USER" ADD CONSTRAINT "PK_EWE_USER" PRIMARY KEY ("ID");

-- ----------------------------
-- Checks structure for table EWE_USER
-- ----------------------------
ALTER TABLE "SCOTT"."EWE_USER" ADD CONSTRAINT "SYS_C0010231" CHECK ("ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_USER" ADD CONSTRAINT "SYS_C0010232" CHECK ("USER_NO" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."EWE_USER" ADD CONSTRAINT "SYS_C0010233" CHECK ("USER_NAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_LOG
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_LOG" ADD CONSTRAINT "PK_UPMS_LOG" PRIMARY KEY ("LOG_ID");

-- ----------------------------
-- Checks structure for table UPMS_LOG
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_LOG" ADD CONSTRAINT "SYS_C0010235" CHECK ("LOG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_LOG" ADD CONSTRAINT "SYS_C0011890" CHECK ("LOG_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_ORGANIZATION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_ORGANIZATION" ADD CONSTRAINT "PK_UPMS_ORGANIZATION" PRIMARY KEY ("ORGANIZATION_ID");

-- ----------------------------
-- Checks structure for table UPMS_ORGANIZATION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_ORGANIZATION" ADD CONSTRAINT "SYS_C0010238" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_PERMISSION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_PERMISSION" ADD CONSTRAINT "PK_UPMS_PERMISSION" PRIMARY KEY ("PERMISSION_ID");

-- ----------------------------
-- Checks structure for table UPMS_PERMISSION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_PERMISSION" ADD CONSTRAINT "SYS_C0010240" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_PERMISSION" ADD CONSTRAINT "SYS_C0010241" CHECK ("SYSTEM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_ROLE" ADD CONSTRAINT "PK_UPMS_ROLE" PRIMARY KEY ("ROLE_ID");

-- ----------------------------
-- Checks structure for table UPMS_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_ROLE" ADD CONSTRAINT "SYS_C0010243" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_ROLE" ADD CONSTRAINT "SYS_C0010244" CHECK ("CTIME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_ROLE" ADD CONSTRAINT "SYS_C0010245" CHECK ("ORDERS" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_ROLE_PERMISSION" ADD CONSTRAINT "PK_UPMS_ROLE_PERMISSION" PRIMARY KEY ("ROLE_PERMISSION_ID");

-- ----------------------------
-- Checks structure for table UPMS_ROLE_PERMISSION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C0010247" CHECK ("ROLE_PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C0010248" CHECK ("ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_ROLE_PERMISSION" ADD CONSTRAINT "SYS_C0010249" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_SYSTEM
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_SYSTEM" ADD CONSTRAINT "PK_UPMS_SYSTEM" PRIMARY KEY ("SYSTEM_ID");

-- ----------------------------
-- Checks structure for table UPMS_SYSTEM
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_SYSTEM" ADD CONSTRAINT "SYS_C0010251" CHECK ("SYSTEM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_SYSTEM" ADD CONSTRAINT "SYS_C0011905" CHECK ("SYSTEM_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_USER
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER" ADD CONSTRAINT "PK_UPMS_USER" PRIMARY KEY ("USER_ID");

-- ----------------------------
-- Checks structure for table UPMS_USER
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER" ADD CONSTRAINT "SYS_C0010254" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER" ADD CONSTRAINT "SYS_C0010255" CHECK ("USERNAME" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER" ADD CONSTRAINT "SYS_C0010256" CHECK ("PASSWORD" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_USER_ORGANIZATION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER_ORGANIZATION" ADD CONSTRAINT "PK_UPMS_USER_ORGANIZATION" PRIMARY KEY ("USER_ORGANIZATION_ID");

-- ----------------------------
-- Checks structure for table UPMS_USER_ORGANIZATION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER_ORGANIZATION" ADD CONSTRAINT "SYS_C0010258" CHECK ("USER_ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER_ORGANIZATION" ADD CONSTRAINT "SYS_C0010259" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER_ORGANIZATION" ADD CONSTRAINT "SYS_C0010260" CHECK ("ORGANIZATION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_USER_PERMISSION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER_PERMISSION" ADD CONSTRAINT "PK_UPMS_USER_PERMISSION" PRIMARY KEY ("USER_PERMISSION_ID");

-- ----------------------------
-- Checks structure for table UPMS_USER_PERMISSION
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER_PERMISSION" ADD CONSTRAINT "SYS_C0010262" CHECK ("USER_PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER_PERMISSION" ADD CONSTRAINT "SYS_C0010263" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER_PERMISSION" ADD CONSTRAINT "SYS_C0010264" CHECK ("PERMISSION_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER_PERMISSION" ADD CONSTRAINT "SYS_C0010265" CHECK ("TYPE" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Primary Key structure for table UPMS_USER_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER_ROLE" ADD CONSTRAINT "PK_UPMS_USER_ROLE" PRIMARY KEY ("USER_ROLE_ID");

-- ----------------------------
-- Checks structure for table UPMS_USER_ROLE
-- ----------------------------
ALTER TABLE "SCOTT"."UPMS_USER_ROLE" ADD CONSTRAINT "SYS_C0010267" CHECK ("USER_ROLE_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
ALTER TABLE "SCOTT"."UPMS_USER_ROLE" ADD CONSTRAINT "SYS_C0010268" CHECK ("USER_ID" IS NOT NULL) NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;

-- ----------------------------
-- Foreign Keys structure for table EMP
-- ----------------------------
ALTER TABLE "SCOTT"."EMP" ADD CONSTRAINT "FK_DEPTNO" FOREIGN KEY ("DEPTNO") REFERENCES "DEPT" ("DEPTNO") NOT DEFERRABLE INITIALLY IMMEDIATE NORELY VALIDATE;
